### PR TITLE
 `import visa` -> `import pyvisa as visa`

### PR DESCRIPTION
**Pull request by doddgray**
The goal of this pull request simply to replace all instances of `import visa` with `import pyvisa as visa`, which is required for use with the current PyVISA release. This change fixed my ability to identify visa instruments with instrumental. 

Let me know if any changes are needed. Thanks!

### CODE REVIEW

**Comment by natezb** [comment]
Cool, thanks. Would you be able to modify this to just `import pyvisa` to make this more standard? The corresponding references to `visa` would then obviously also have to be changed to `pyvisa` to match

**Comment by doddgray** [comment]
Sure, I can do that. I felt a bit unsure whether all mentions of `visa` (sometimes strings, kwargs, keys in dicts etc.) in the code base could safely be changed to `pyvisa`. But I will give this a try.

**Comment by natezb** [comment]
I would generally start with the files you've modified here, and probably not modify any strings unless it clearly makes sense to.

You may be able to use a refactor tool in your editor to change `import visa` to `import pyvisa` and update all the references.

**Comment by robotanik** [comment]
Since I tried to use it, I noticed the change is still missing in the `drivers/spectrometers/thorlabs_ccs.py` file. You may have to check for all instances of `from visa import` as well.

**Pull request merged**
