### PR TITLE
[cameras.pco] Add broader support for PCO cameras

### PR DESCRIPTION
**Pull request by natezb**
Kicked off by #104. Let's use this branch/PR to collect changes related to adding broader support for different camera models supported by the PCO sdk.

### CODE REVIEW

**Comment by zakv** [comment]
For reference I've attached some of the code that I edited or wrote here: [pco_sdk_wrappers.txt](https://github.com/mabuchilab/Instrumental/files/3992399/pco_sdk_wrappers.txt). I had to change the extension to ".txt" so that Github would let me attach it, but it should really end in ".py". Feel free to take anything in there and include it in Instrumental. Additionally, I have some other code which serves a similar purpose to Instrumental's `PCO_Camera` class, but is written to provide the required methods for interacting with Labscript. I'd be happy to share that file as well if you'd like it for reference or to include any of its code.

Below are lists of the bugs that I ran into and some other enhancements that I needed.

Module-Level:
- [ ] Whenever I import `instrumental.drivers.cameras.pco` I get the warning below. It doesn't seem to cause any issues, but I mention it here for completeness.
```
C:\Users\Rubidium\Software\Anaconda3\lib\site-packages\cffi\cparser.py:150: UserWarning: String literal found in cdef() or type source. String literals are ignored here, but you should remove them anyway because some character sequences confuse pre-parsing.
  warnings.warn("String literal found in cdef() or type source. "
```

PCO_Camera Class:
- [ ] The line `y1 = min(self.max_width, y1)` around line 304 should use `self.max_height` instead of `self.max_width`
- [ ] `PCO_Camera._data_depth()` didn't work. The pixelfly USB is 14 bit and doesn't have a corresponding entry in the `depth_map` dictionary. It looks like this method just needs to figure out the bit depth of the camera's ADC? If so it might just be easier to use `self._get_camera_description().wDynResDESC`
- [ ] Calling `camera_inst.grab_image()` calls `self._allocate_buffers`, which calls `self._cam.SetRecordingState(0)`, which causes the code to error out. The error is actually just a warning from the PCO SDK function which says that the recording state is already set to zero. This can be avoided by just putting that call in a `if self._cam.GetRecordingState():` conditional statement so that it's only run if the recording state isn't already zero.


NiceLib and NiceObject Issues:
- [ ] I ended up needing some additional functions from the PCO SDK, so I wrote new `Sig`'s for them. I also tried to organize all of the `Sig`'s nicely, putting them in the same order as the appear in the PCO SDK manual and separating them by which chapter they appeared in.
- [ ] The `_struct_maker_()` method errors on some methods (possibly only on some of the ones I added) because some structs actually don't have a `wSize` parameter. Editing the code to check if the structs have that property using `hasattr()` resolved that issue.
- [ ] It looks like `GetTransferParameter()` assumes that the camera is connected via Camera Link, judging by the struct type that `params_p` points to. I ended up not needing this function for my purposes, but I wrote a version which selects the struct type based on the camera interface type (although I wasn't sure what type to use for the serial interface). It's in the attached file.


Other Enhancements:
- [ ] I wrote a `PCOError` class for handling the error codes returned by the PCO SDK. It works around the issue mentioned here https://github.com/mabuchilab/Instrumental/issues/30 by presenting the error's hex code to the user if the compiled `GetErrorText()` function isn't available. It also has methods for converting error codes to/from strings of hex characters which can be helpful for e.g. catching only certain PCO SDK errors. It's not required but I found it pretty helpful and might be worth including in Instrumental.

**Comment by natezb** [comment]
Sorry this got buried in my inbox! I think a fork would be great, so we can discuss the changes and merge them in using a PR. By the looks of your previous message you have a very good grasp of what's going on, so the only thing I'd really suggest at this point is that each commit in your fork should be relatively self-contained, much as you've organized things above.

**Comment by zakv** [comment]
Hi Nate,

Sorry for the long message, but I've forked the repo (https://github.com/zakv/Instrumental/tree/pco) and implemented the changes listed above. At that point many things were still not working, so I made the following additional changes:

* In `pco.PCO_Camera.set_trigger_mode()`, `GetHWIOSignal()` and `SetHWIOSignal()` are now only called if the camera supports it.
* In `pco.PCO_Camera.start_capture()`, if the camera is recording it is now stopped before trying to arm it.
* `pco.PCO_Camera._get_sizes()` now appropriately handles cameras that support double image mode.
* `pco.PCO_Camera._frame_size()` now always allocates an integer number of bytes per pixel.
* `pco.PCO_Camera.start_capture()` now handles non-camera-link-cameras appropriately.
  * It avoids calling camera-link-only functions now
  * It also calls `SetRecordingState(1)` before `self._push_on_queue()` for non-camera-link-cameras, which seems wrong but is correct according to the `PCO_AddBufferEx()` documentation
    * I also verified in tests that doing it in the intuitive order used for camera link causes errors for our non-camera-link-camera. 
* `pco.PCO_Camera.start_live_video()` now catches error thrown when camera doesn't support `SetFrameRate()`.
* `pco.PCO_Camera.start_live_video()` now handles non-camera-link-cameras appropriately.

After those changes, the `PCO_Camera` methods `grab_image()`, `start_live_video()`, `wait_for_frame()`, `latest_frame()`, and `stop_live_video` all work with the pixelfly usb. For completeness I should also mention the following:

* Right now the error thrown in `pco.PCO_Camera.start_live_video()` when a camera doesn't support `SetFrameRate()` is just silently ignored.
  * This in turn means that the `framerate` input is silently ignored in that case, which really isn't ideal but I'm not sure what's the best way to handle that. I'd be happy to have your input here if you have any suggestions.
* `instrumental.drivers.cameras.Camera._handle_kwds()` doesn't handle odd numbers for `'width'` and `'height'` well when edges (e.g. `'top'` or `'left'`) aren't given.
  * e.g. {'width':101, 'height':301} makes 'left': 645.5 which causes an indexing error later on.
  * I think this would affect other cameras as well so I wasn't sure if this pull request was the appropriate place to fix it.
  * This may be a Python 2/3 issue where "`/`" was integer division in 2 but not in 3.

I'm not sure how to merge these changes in. Should I submit a different PR from my fork? Or would you like to merge my fork's edits into this PR? Of course, let me know if you'd like any changes before merging.

Cheers,
Zak

**Comment by natezb** [comment]
> * Right now the error thrown in pco.PCO_Camera.start_live_video() when a camera doesn't support SetFrameRate() is just silently ignored.
>   * This in turn means that the framerate input is silently ignored in that case, which really isn't ideal but I'm not sure what's the best way to handle that. I'd be happy to have your input here if you have any suggestions.

It's probably ok as-is, but one idea is to check if `framerate` is explicitly passed in by checking `kwds` (before the call to `_handle_kwds()`), and set a `explicit_framerate` boolean flag. Then we ignore the framerate error only if that flag is false.

> * `instrumental.drivers.cameras.Camera._handle_kwds()` doesn't handle odd numbers for `'width'` and `'height'` well when edges (e.g. `'top'` or `'left'`) aren't given.
>   * e.g. {'width':101, 'height':301} makes 'left': 645.5 which causes an indexing error later on.
>   * I think this would affect other cameras as well so I wasn't sure if this pull request was the appropriate place to fix it.
>   * This may be a Python 2/3 issue where "`/`" was integer division in 2 but not in 3.

Yeah, it looks like all of those `width/2`'s in `fill_all_coords()` should be changed to explicit floor division `width//2`'s.

>I'm not sure how to merge these changes in.

I just added you as a contributor with write access, so you should be able to push directly to our repo. I'd suggest you push the changes from your fork to this branch (`pco`), and we can review them here in this PR before merging with `master`. Welcome to the team!

**Comment by zakv** [comment]
Hi Nate,

Thanks!

I like the `explicit_framerate` idea, but I haven't figured out a good way to implement it because the method declaration has `framerate='10Hz'` explicitly specified in it (see e.g. https://stackoverflow.com/questions/14749328/how-to-check-whether-optional-function-parameter-is-set). I tried changing it to `framerate=None` and then adjusting the method to default to `'10Hz'` when `framerate` is `None`, so that it would be possible to tell if the user specified a `framerate` or not. Unfortunately then the `@check_units` decorator wasn't happy because `None` doesn't have units of Hz. As a workaround I just set it to issue a warning if the camera doesn't support `PCO_SetFrameRate()`, and provided an `enable_framerate_warning` optional input to suppress the warning if desired.

Also, on my machine the `errortext.pyd` file generated was actually called `errortext.cp37-win_amd64.pyd` so I added `errortext.*.pyd` to `.gitignore` just below the entry for `errortext.pyd`.

I'll push these changes to the pco branch, then open a separate PR for the Python 2/3 floor division issue so that either can be reverted independently of the other if necessary.

Cheers,
Zak

Changes:
* `pco.PCO_Camera.start_live_video()` now issues a warning if the camera does not support a fixed frame rate.
  * An optional `enable_framerate_warning` argument makes it possible to suppress this warning.
* Added `errortext.*.pyd` to `.gitignore`.

**Comment by natezb** [comment]
Thanks, I'll try to review this tonight.

**Comment by natezb** [comment]
Looks good to me except for the framerate issue. I believe what you tried (setting the default to `framerate=None` and handling it in the function) should work as long if you prepend '?' to the unit spec, i.e. use `@check_units(framerate='?Hz')`, which allows the arg to be optional.

**Comment by zakv** [comment]
Sounds good, incorporated into the latest commit.

**Pull request merged**
