### PR TITLE
Unsophisticated patch for devices with no digital ports

### PR DESCRIPTION
**Pull request by danieldmulkey**

### CODE REVIEW

**Comment by natezb** [comment]
Hey Daniel, thanks for noticing and fixing this!

I think we can even fix this one level up: there are several times where we use `GetSomeBytes().decode().split(',')` to split up a comma-delimited string. Unfortunately, `split(',')` will produce a non-empty list even when invoked on an empty string. It's probably best if we write a little helper function for doing the proper thing for all of these strings.

Can you tell me what `daq._dev.GetDevDILines()` returns for your DAQ? I'm wondering whether it's an empty string, or if there's always a comma included.

**Comment by danieldmulkey** [comment]
Hi Nate,

That command returns:

b''

for me (empty binary string?). I'm on anaconda 3.6 and instrumental 0.5.

Cheers,
-Daniel

**Comment by natezb** [comment]
I just pushed some new code implementing the fix I described above (a76ef03e411bedd74c1db0029f421bf211b10c2c). If you get a chance, give it a try and let me know if it resolves your issue.

**Comment by danieldmulkey** [comment]
Looks good, thanks Nate!

Cheers,

**Comment by natezb** [comment]
Awesome, be sure to let us know if you have any other issues.

**Pull request closed without merging**
